services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: sam
      POSTGRES_PASSWORD: FGRY14f3QXIzZP+ZUqyGX6HI0hstfMNQZL3+wZwQJQ=
      POSTGRES_DB: portfolio
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: